# Generated by Django 4.2 on 2023-06-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like_alreadyliked_post_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='alreadyLiked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_likes',
        ),
    ]
