# Generated by Django 4.2 on 2023-06-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_like_alreadyliked_remove_post_user_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
